# SPDX-FileCopyrightText: 2023-2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
# SPDX-FileCopyrightText: 2026 spatterlight
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
# This task does not explicitly set permissions since doing so resolves an idempotency issue
- name: Ensure Wazuh manager data directories exist # noqa: risky-file-permissions
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ wazuh_data_path }}/manager"
    - "{{ wazuh_data_path }}/manager/api_configuration"
    - "{{ wazuh_data_path }}/manager/etc"
    - "{{ wazuh_data_path }}/manager/etc/rules"
    - "{{ wazuh_data_path }}/manager/etc/shared"
    - "{{ wazuh_data_path }}/manager/etc/shared/default"
    - "{{ wazuh_data_path }}/manager/logs"
    - "{{ wazuh_data_path }}/manager/queue"
    - "{{ wazuh_data_path }}/manager/var_multigroups"
    - "{{ wazuh_data_path }}/manager/integrations"
    - "{{ wazuh_data_path }}/manager/active_response"
    - "{{ wazuh_data_path }}/manager/agentless"
    - "{{ wazuh_data_path }}/manager/wodles"
    - "{{ wazuh_data_path }}/manager/filebeat_etc"
    - "{{ wazuh_data_path }}/manager/filebeat_var"

- name: Ensure Wazuh manager temporary configuration directory exists
  ansible.builtin.tempfile:
    state: directory
    suffix: wazuh-manager
  changed_when: false
  register: wazuh_manager_tempdir

- name: Copy Wazuh manager default ossec.conf for customization
  ansible.builtin.copy:
    src: "{{ role_path }}/files/conf/manager/wazuh_manager.conf"
    dest: "{{ wazuh_manager_tempdir.path }}/wazuh_manager.conf"
    mode: "0640"
    owner: "{{ wazuh_manager_uid }}"
    group: "{{ wazuh_manager_gid }}"
  changed_when: false

# This is hacky work-around due to deal w/ the official Wazuh XML not being compatible with Python's lxml
# TODO -> Find a better solution?
- name: Wrap Wazuh manager config in temporary XML root for multi-document support
  ansible.builtin.lineinfile:
    path: "{{ wazuh_manager_tempdir.path }}/wazuh_manager.conf"
    line: "{{ item.line }}"
    insertbefore: "{{ item.insertbefore | default(omit) }}"
    insertafter: "{{ item.insertafter | default(omit) }}"
  changed_when: false
  loop:
    - line: "<wazuh_root>"
      insertbefore: BOF
    - line: "</wazuh_root>"
      insertafter: EOF

- name: Ensure Wazuh manager ossec.conf has the defined adjustments
  community.general.xml:
    path: "{{ wazuh_manager_tempdir.path }}/wazuh_manager.conf"
    xpath: "{{ item.xpath | regex_replace('^/ossec_config', '/wazuh_root/ossec_config') }}"
    value: "{{ item.value | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    pretty_print: "{{ item.pretty_print | default(false) }}"
  changed_when: false
  with_items: "{{ wazuh_manager_ossec_xml_replacements }}"

- name: Remove temporary XML root wrapper from Wazuh manager config
  ansible.builtin.lineinfile:
    path: "{{ wazuh_manager_tempdir.path }}/wazuh_manager.conf"
    regexp: "^</?wazuh_root>\\s*$"
    state: absent
  changed_when: false

- name: Remove XML declaration added by lxml from Wazuh manager config
  ansible.builtin.lineinfile:
    path: "{{ wazuh_manager_tempdir.path }}/wazuh_manager.conf"
    regexp: "^<\\?xml"
    state: absent
  changed_when: false

- name: Ensure Wazuh manager ossec.conf is installed
  ansible.builtin.copy:
    src: "{{ wazuh_manager_tempdir.path }}/wazuh_manager.conf"
    dest: "{{ wazuh_data_path }}/manager/etc/ossec.conf"
    remote_src: true
    mode: "0640"
    owner: "{{ wazuh_manager_uid }}"
    group: "{{ wazuh_manager_gid }}"
  register: wazuh_manager_config_result

- name: Ensure Wazuh manager environment file is installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/manager/env.j2"
    dest: "{{ wazuh_base_path }}/manager.env"
    mode: "0600"
    owner: root
    group: root
  register: wazuh_manager_env_result

- name: Ensure Wazuh manager container image is pulled via community.docker.docker_image_pull
  when: devture_systemd_docker_base_container_image_pull_method == 'ansible-module'
  community.docker.docker_image_pull:
    name: "{{ wazuh_manager_container_image }}"
    pull: always
  register: wazuh_manager_container_image_pull_result_ansible_module
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: wazuh_manager_container_image_pull_result_ansible_module is not failed

- name: Ensure Wazuh manager container image is pulled via ansible.builtin.command
  when: devture_systemd_docker_base_container_image_pull_method == 'command'
  ansible.builtin.command:
    cmd: "{{ devture_systemd_docker_base_host_command_docker }} pull {{ wazuh_manager_container_image }}"
  register: wazuh_manager_container_image_pull_result_command
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: wazuh_manager_container_image_pull_result_command is not failed
  changed_when: "'Downloaded newer image' in wazuh_manager_container_image_pull_result_command.stdout"

- name: Ensure Wazuh manager systemd service is installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/wazuh-manager.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ wazuh_manager_identifier }}.service"
    mode: "0644"
  register: wazuh_manager_systemd_service_result

- name: Ensure Wazuh manager systemd service is enabled
  ansible.builtin.systemd:
    name: "{{ wazuh_manager_identifier }}.service"
    enabled: true
    daemon_reload: true

- name: Determine whether Wazuh manager needs a restart
  ansible.builtin.set_fact:
    wazuh_manager_restart_necessary: >-
      {{
        wazuh_manager_config_result.changed | default(false)
        or wazuh_manager_env_result.changed | default(false)
        or wazuh_manager_systemd_service_result.changed | default(false)
        or wazuh_manager_container_image_pull_result_ansible_module.changed | default(false)
        or wazuh_manager_container_image_pull_result_command.changed | default(false)
      }}

- name: Notify about Wazuh manager needing restart
  when: wazuh_manager_restart_necessary | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: The Wazuh manager configuration has changed. Restart the `" ~ wazuh_manager_identifier ~ ".service` systemd service to apply changes."
        ]
      }}
