# SPDX-FileCopyrightText: 2023 - 2024 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
# SPDX-FileCopyrightText: 2026 spatterlight
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Stop and remove Wazuh systemd services
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall_unit.yml"
  loop:
    - "{{ wazuh_manager_identifier }}.service"
    - "{{ wazuh_indexer_identifier }}.service"
    - "{{ wazuh_dashboard_identifier }}.service"
    - "wazuh-certs-generator.service"
  loop_control:
    loop_var: wazuh_unit_name

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Check existence of Wazuh local data path
  ansible.builtin.stat:
    path: "{{ wazuh_data_path }}"
  register: wazuh_data_path_stat

- name: Notify about remaining Wazuh data
  when: wazuh_data_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local Wazuh instance has been removed, some old data remains in `" + wazuh_data_path + "`. Feel free to delete it."
        ]
      }}

- name: Remove Wazuh container network via community.docker.docker_network
  when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
  community.docker.docker_network:
    name: "{{ wazuh_container_network }}"
    state: absent
  failed_when: false

- name: Remove Wazuh container network via ansible.builtin.command
  when: devture_systemd_docker_base_container_network_creation_method == 'command'
  ansible.builtin.command:
    cmd: "{{ devture_systemd_docker_base_host_command_docker }} network rm {{ wazuh_container_network }}"
  register: wazuh_network_removal_result
  changed_when: wazuh_container_network in wazuh_network_removal_result.stdout
  failed_when: false
