# SPDX-FileCopyrightText: 2026 spatterlight
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Apply devture base roles and Wazuh role
  hosts: all
  become: true
  gather_facts: true
  vars:
    wazuh_indexer_admin_password: "-e99_t)IpGfN(fFyo(oq<u`%gHA~m~dWY9CGG#&*%832RfZWH:SnkvTxYQn3RBwR"
    wazuh_indexer_kibanaserver_password: "MVbD1iNV@t`0+Ix>kO-A7uvnAhJ:/yGzG(P.%Lg8luzJt4jSZy5hTfculf9!few="
    wazuh_manager_api_password: "e.>*<DheN[S&uZn&>u<~l!ffio`e%%0Dx#avY(tUb-DIUXC&@fQ_)=jH[WE^G<zX"
    wazuh_manager_indexer_password: "ij1S@ePWtD0;0ioxLaEp]Gp#Z4(pdy,Qpz,AufVYo-YTT57^i(u4lS22qc`ThX*6"

    wazuh_indexer_admin_password_salt: "3tYCPUOl9UOjLWVjKptmvf"
    wazuh_indexer_kibanaserver_password_salt: "xRA72EkyJEHeYwM4jSxVK6"

    wazuh_dashboard_container_labels_traefik_enabled: false
    wazuh_dashboard_http_host_bind_port: "80"
  tasks:
    - name: Include roles
      ansible.builtin.include_role:
        name: "{{ role_name }}"
        public: true
      loop:
        - com.devture.ansible.role.playbook_help
        - com.devture.ansible.role.systemd_docker_base
        - "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      loop_control:
        loop_var: role_name

- name: Start Wazuh services
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Start wazuh-indexer service
      ansible.builtin.systemd:
        name: wazuh-indexer.service
        state: started
        daemon_reload: true

    - name: Start wazuh-manager service
      ansible.builtin.systemd:
        name: wazuh-manager.service
        state: started

    - name: Start wazuh-dashboard service
      ansible.builtin.systemd:
        name: wazuh-dashboard.service
        state: started
