# SPDX-FileCopyrightText: 2026 spatterlight
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: wazuh-${MOLECULE_DISTRO:-ubuntu2404}-default
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2404}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    published_ports:
      - 127.0.0.1:8080:80
      - 127.0.0.1:8443:443
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_result_format: yaml
  # This is a hack to resolve https://github.com/ansible/molecule/issues/4391
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/..:/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:~/.ansible/roles
verifier:
  name: ansible
