---
- name: Prepare Wazuh host
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: Install Docker
      ansible.builtin.include_role:
        name: ansible-role-docker
      vars:
        docker_daemon_options:
          storage-driver: vfs
