---
###########
## Roles ##
###########

roles:
  - name: ansible-role-docker
    src: https://github.com/geerlingguy/ansible-role-docker
    scm: git
    version: master

  - name: com.devture.ansible.role.playbook_help
    src: https://github.com/devture/com.devture.ansible.role.playbook_help
    scm: git
    version: main

  - name: com.devture.ansible.role.systemd_docker_base
    src: https://github.com/devture/com.devture.ansible.role.systemd_docker_base
    scm: git
    version: main

  - name: ansible-role-traefik
    src: https://github.com/mother-of-all-self-hosting/ansible-role-traefik
    scm: git
    version: main

#################
## Collections ##
#################

collections:
  - name: https://github.com/ansible-collections/community.docker
    type: git
    version: main

  - name: https://github.com/ansible-collections/community.general
    type: git
    version: main

  - name: https://github.com/ansible-collections/ansible.posix
    type: git
    version: main
