# SPDX-FileCopyrightText: 2026 spatterlight
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: wazuh-${MOLECULE_DISTRO:-ubuntu2604}-features
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2604}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    published_ports:
      - 127.0.0.1:8080:80
      - 127.0.0.1:8443:443
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_result_format: yaml
  inventory:
    group_vars:
      all:
        wazuh_indexer_admin_password: "c8ww87xpBnC0ao1p3WL1OCoCGXwgCDYpa11cjT1Y3dP1xY6g7zUyGZSNgafDrTK!"
        wazuh_indexer_kibanaserver_password: "EZBcxkhqV6gsaKZPg6wJGG66TUqJXpmFCHs1xSNsVoRsoue7ZpEzj9kR2G7Wz8V!"
        wazuh_manager_api_password: "Cw7pBmlsnBGXreGfVN8GGrwoYvI03D3XuvEMo6MJ53nhez7tqElJPmitz2At5Ot!"

        wazuh_indexer_admin_password_salt: "3tYCPUOl9UOjLWVjKptmvf"
        wazuh_indexer_kibanaserver_password_salt: "xRA72EkyJEHeYwM4jSxVK6"

        wazuh_dashboard_container_labels_traefik_enabled: false
        wazuh_dashboard_http_host_bind_port: "80"

        wazuh_indexer_opensearch_java_opts: "-Xms512m -Xmx512m"

        wazuh_enrollment_password: eHpdDqve4PdYlmEtcLRnWzP2yEVDGMv3oUKlwsVrev81EQxHD2Rpm37HfDCnuk2X

        wazuh_agent_conf: |
          <agent_config name="92603de31548">
            <labels>
              <label key="aws.instance-id">i-052a1838c</label>
              <label key="aws.sec-group">sg-1103</label>
              <label key="network.ip">172.17.0.0</label>
              <label key="network.mac">02:42:ac:11:00:02</label>
              <label key="installation" hidden="yes">July 1st, 2024</label>
            </labels>
          </agent_config>

        wazuh_rules:
          - file: local_rules.xml
            contents: |
              <group name="local,">
                <rule id="100001" level="3">
                  <description>Custom rule example</description>
                </rule>
              </group>

        wazuh_integrations:
          - name: custom-element
            src: "{{ role_path }}/files/integrations/element/custom-element"
            mode: "0750"
          - name: custom-element.py
            src: "{{ role_path }}/files/integrations/element/custom-element.py"
            mode: "0750"

  env:
    # This is a hack to resolve https://github.com/ansible/molecule/issues/4391
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/..:/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:~/.ansible/roles
verifier:
  name: ansible
