---
name: pre-commit

on: [push, pull_request]

jobs:
  build:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Ansible collections
        run: |
          pip install ansible-core
          ansible-galaxy collection install -r molecule/default/requirements.yml

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
